services:
  db:
    image: postgres:18.3-alpine
    environment:
      - POSTGRES_DB=prevently
      - POSTGRES_USER=prevently
      - POSTGRES_PASSWORD=prevently
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db_data: