FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download -x

COPY . .
RUN CGO_ENABLED=0 go build -o worker ./cmd/worker

FROM alpine:3.23

WORKDIR /app
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/worker /usr/local/bin/worker

RUN adduser -D worker
USER worker

ENTRYPOINT ["/usr/local/bin/worker"]