FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download -x

COPY . .
RUN CGO_ENABLED=0 go build -o api ./cmd/api

FROM alpine:3.23

WORKDIR /app
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/api /usr/local/bin/api

RUN adduser -D api
USER api

ENTRYPOINT ["/usr/local/bin/api"]