// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, name, type, config)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, type, config, created_at
`

type CreateDeviceParams struct {
	UserID string
	Name   string
	Type   string
	Config []byte
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Config,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, name, type, config, created_at
FROM devices
WHERE user_id = $1
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
