// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID        string
	UserID    string
	Name      string
	Type      string
	Config    []byte
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        string
	Email     string
	ApiKey    string
	CreatedAt pgtype.Timestamptz
}
