// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pushes.sql

package db

import (
	"context"
)

const createPush = `-- name: CreatePush :one
INSERT INTO pushes (user_id, message)
VALUES ($1, $2)
RETURNING id, user_id, message, status, attempts, last_error, created_at, sent_at
`

type CreatePushParams struct {
	UserID  string
	Message string
}

func (q *Queries) CreatePush(ctx context.Context, arg CreatePushParams) (Push, error) {
	row := q.db.QueryRow(ctx, createPush, arg.UserID, arg.Message)
	var i Push
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}
