name: Build and push Docker images

on:
  push:
    branches: [ "main" ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    strategy:
      matrix:
        include:
          - service: api
            dockerfile: Dockerfile.api
          - service: worker
            dockerfile: Dockerfile.worker
            
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
          
      - name: Extract meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}

      - name: Build and push images
        uses: docker/build-push-action@v7
        with:
          push: true
          context: .
          file: ./${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
